version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  summarization:
    executor: node/default
    working_directory: ~/cookbook/demos
    steps:
      - checkout:
          path: ~/cookbook
      - run:
          name: Install Okareo CLI
          command: |
              curl -O -L https://github.com/okareo-ai/okareo-cli/releases/download/v0.0.14/okareo_0.0.14_linux_386.tar.gz
              tar -xvf okareo_0.0.14_linux_386.tar.gz
              chmod +x bin/okareo
              echo 'export PATH=$PATH:$PWD/bin' >> $BASH_ENV
      - run:
          name: Check Okareo Version
          command: okareo --version
      - run:
          name: Run Summarization
          command: okareo run -f summarization

  classification:
    executor: node/default
    working_directory: ~/cookbook/demos
    steps:
      - checkout:
          path: ~/cookbook
      - run:
          name: Install Okareo CLI
          command: |
              curl -O -L https://github.com/okareo-ai/okareo-cli/releases/download/v0.0.14/okareo_0.0.14_linux_386.tar.gz
              tar -xvf okareo_0.0.14_linux_386.tar.gz
              chmod +x bin/okareo
              echo 'export PATH=$PATH:$PWD/bin' >> $BASH_ENV
      - run:
          name: Check Okareo Version
          command: okareo --version
      - run:
          name: Run Classification
          command: okareo run -f classification

  reporting:
    executor: node/default
    working_directory: ~/cookbook/demos
    steps:
      - checkout:
          path: ~/cookbook
      - run:
          name: Install Okareo CLI
          command: |
              curl -O -L https://github.com/okareo-ai/okareo-cli/releases/download/v0.0.14/okareo_0.0.14_linux_386.tar.gz
              tar -xvf okareo_0.0.14_linux_386.tar.gz
              chmod +x bin/okareo
              echo 'export PATH=$PATH:$PWD/bin' >> $BASH_ENV
      - run:
          name: Check Okareo Version
          command: okareo --version
      - run:
          name: Summarization Report
          command: okareo run -f x_summarization_logger
      - run:
          name: Classification Report
          command: okareo run -f x_classification_logger

  cookbook-test:
    executor: node/default
    working_directory: ~/cookbook
    steps:
      - checkout:
          path: ~/cookbook
      - run:
          name: Install Okareo CLI
          command: |
              curl -O -L https://github.com/okareo-ai/okareo-cli/releases/download/v0.0.14-alpha/okareo_0.0.14-alpha_linux_386.tar.gz
              tar -xvf okareo_0.0.14-alpha_linux_386.tar.gz
              chmod +x bin/okareo
              echo 'export PATH=$PATH:$PWD/bin' >> $BASH_ENV
      - run:
          name: Check Okareo Version
          command: okareo --version
      - run:
          name: Run Cookbook Test
          command: okareo run -d -f example

workflows:
  version: 2
  build:
    jobs:
      - cookbook-test:
          context:
            - Demo-Env
#      - summarization:
#          context:
#            - Demo-Env
#      - classification:
#          context:
#            - Demo-Env
#      - reporting:
#          requires:
#            - "summarization"
#            - "classification"
#          context:
#            - Demo-Env
